### ISSUE TITLE
App does not work on clean installation

### ISSUE THREAD

**Issue by leechwort** [hacklabkyiv/prismo#15]
Discovered on @temhota  MacOS machine. After clean installation and putting config, app does not start with such error:
```
Traceback (most recent call last):
  File "/Users/temho/hacklab/virtualenv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/flask/cli.py", line 1064, in main
    cli.main()
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/click/decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/flask/cli.py", line 912, in run_command
    raise e from None
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/flask/cli.py", line 898, in run_command
    app = info.load_app()
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/flask/cli.py", line 309, in load_app
    app = locate_app(import_name, name)
  File "/Users/temho/hacklab/virtualenv/lib/python3.9/site-packages/flask/cli.py", line 219, in locate_app
    import(module_name)
  File "/Users/temho/hacklab/application.py", line 16, in <module>
    from app.data.work_logs_repository import get_full_logs, get_latest_key
  File "/Users/temho/hacklab/app/data/work_logs_repository.py", line 6, in <module>
    def get_latest_key() -> str | None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

I cannot reproduce on my machine.

**Comment by VovaStelmashchuk** [comment]
Looks like your Python version is 3.9 or less, The union X | Y supports in python version 3.10, execute the `python --version ` to check your a python version and be sure our version 3.10 or above

**Comment by VovaStelmashchuk** [comment]
Can we close the issue?

**Comment by temhota** [comment]
> Can we close the issue?

sure. thank you for response
